### ISSUE TITLE
Update home page to feature install script for 0.0.3

### ISSUE THREAD

**Issue by gabek** [owncast/owncast.github.io#11]
For release 0.0.3 we'll have the nice install script #7 and planning for a quick video showing how easy it is to install https://github.com/owncast/owncast/issues/257.

I don't know exactly what the page should consist of going forward, but maybe it's time to update the home page to feature the "easy to setup" nature of Owncast since it's getting to the point where it's appealing to more people.  It's still primarily a documentation page of course, but it's also our public presence until some point in the future when we want a "marketing" site that has a different target audience.

I still think it's worthwhile having a blurb on the home page explaining who it's useful for up front without making them dig into more docs, but I don't think the long extended story is what we should keep.  Maybe it's too early to be thinking of such things, but maybe a shorter tag line might be helpful.

Example: [Homebrew](https://brew.sh/) does a good job of making the install script instructions the most important thing on the page.  They have a tag line of _"The Missing Package Manager for macOS (or Linux)"_ and it's clear upfront what it does.

Let's discuss and decide how to tweak the home page going forward.

**Comment by gabek** [comment]
As an aside, I just noticed the Caddy v2 site and they do a nice job embedding a setup example.  Scroll down to _A whole new server experience_.  It seems to be all in javascript, very cool!

https://caddyserver.com/v2

**Comment by gabek** [comment]
That asciinema is cool.  Just tried it:

[![asciicast](https://asciinema.org/a/kmFBb2GR8O5aqmHp89FBzw3wo.svg)](https://asciinema.org/a/kmFBb2GR8O5aqmHp89FBzw3wo)

**Comment by mattdsteele** [comment]
Yeah asciinema is fun! And it's just a web component, so it would be easy to embed in Hugo.

The homepage probably has multiple goals from a marketing perspective. A few things we should hit:

* Easy of install - show the install script, etc
* Easy to switch - use the streaming tools you already know (OBS, etc), it's Twitch in a Box
* Easy to try - maybe link to the demo server?
* Easy to customize - embed the chat stream, customize the UI, etc

As we get the directory built out and maybe populated, we could link to that too.

**Comment by gabek** [comment]
Those categories are a really great way to think about it!

I just pushed a `0.0.3` branch that adds a mention of the install script (thanks to @jmhobbs!) on the home page and the quick start, and and asciicast of it in use on the home page.  I'm sure we should re-word things, pretty them up, and organize things a bit, but I just wanted to make a first stab at it.  But anybody is free to iterate on it as they see fit.

Like Matt said, maybe we should add a "Try" page that points to the demo servers.  Though admittedly I find our broadcasting demo server a bit hard to clearly explain.

We can probably rename the "embed" page to "Customize" to have more about the web UI and the options around all those components.  And the [Broadcasting software](https://owncast.online/docs/broadcasting/) can be made a bit friendlier by talking in terms of switching and not just clinical documentation on how to setup pieces of software.  Both are useful.

**Comment by gabek** [comment]
Tweaking.  
![image](https://user-images.githubusercontent.com/414923/98019711-f2d17a00-1db6-11eb-87a1-dcfc1b544537.png)
