### ISSUE TITLE
Improve docs for first time users

### ISSUE THREAD

**Issue by rdtq** [owncast/owncast.github.io#34]
As a first-time user I quickly launched owncast instance with `curl -s https://owncast.online/install.sh | bash`, but spent some time figuring out how to stream to it with OBS.

Is it rtmp:// or http:// ? 8080 or some other port, or no port at all? Also `/live` path was not obvious.

It would help if OBS settings were right next to install script in docs.

**Comment by gabek** [comment]
Just out of curiosity so we can make the documentation better, what led you to not look at the [Quickstart](https://owncast.online/docs/quickstart/) guide?  Is it hard to find?

**Comment by rdtq** [comment]
I don't really remember the details, but when I'm copy-pasting commands I assume it's already a `Quickstart` phase :)

**Comment by gabek** [comment]
Docs specifically have instructions on using OBS, so hopefully things are in a good place.
