### ISSUE TITLE
flv argument in the ffmpeg example command

### ISSUE THREAD

**Issue by pierreozoux** [owncast/owncast.github.io#36]
Sorry it is more a question than an issue.

If I use 3 profiles encoding profiles in owncast, and one of them is passthough for audio and video, wouldnt it be better, resource wise, to already send an hls container?

Or does owncast does recontainerize anyway?

Thanks for clarifying :)

I guess the answer is that, as all popular stream website (youtube..) expect flv, then all clients (obs, zoom..) send flv by default, hence this recommended configuration for ffmpeg.
But if we use ffmpeg and owncast, we can be smarter, but adding the complexity dev and ux wise compared to the cpu cycles gain is the balance to judge, I guess :)

**Comment by pierreozoux** [comment]
Actually reading more it would mean that owncast would have to pull the content instead of receiving a push from the client, which make things a bit harder for some client to be able to expose this file, I think I got it.

**Comment by gabek** [comment]
Oddly enough I heard that YouTube is starting to do a specialized delivery system optionally replacing RTMP with HLS chunks. I don't think it changes what has to happen once it gets ingested, but it's an interesting approach to delivering the content to them.  So in this case they're doing push of HLS.  But I don't see that replacing RTMP anytime soon.

**Comment by pierreozoux** [comment]
Actually reading more it would mean that owncast would have to pull the content instead of receiving a push from the client, which make things a bit harder for some client to be able to expose this file, I think I got it.

**Comment by pierreozoux** [comment]
In there case, a bit of cpu, represents several hundreds of core I guess ;)
