### ISSUE TITLE
Add more Tutorials for media providers

### ISSUE THREAD

**Issue by jeyemwey** [owncast/owncast.github.io#4]
Anyone who tries Owncast with their media generator (video mixing software, hardware stream boxes, you name it) is invited to publish their configuration, so other people can benefit.

If you are willing to write a chapter for our documentation, please reply in this issue - this way, we prevent that several people work on the same mixer.

There are some guidelines:

* The text and all images should be only contain English text.
* All images should be in `/content/docs/img` and have speaking names, in accordance with the images present. Please try to minify the images if they become too large. 
* Please include as many images as necessary and as few images as possible.
* Add your text in `/content/docs/broadcasting.md`. If the file gets too large, we will split it up, but it should be fine for now.

**Comment by gabek** [comment]
This is a fantastic idea, thank you for coming up with it, Jannik!  I wonder if we should update our broadcasting docs page to point to this issue so when people are browsing the documentation about software configuration they know they can help improve it.
